### ISSUE TITLE
CodeSystem.identifier.system krever 'absolute reference'

### ISSUE THREAD

**Issue by rockphotog** [HL7Norway/kodeverk#1]
Feilmelding: `CodeSystem.identifier[0] | error | Identifier.system must be an absolute reference, not a local reference`
Kilde feilmelding: https://hl7norway.github.io/kodeverk/currentbuild/qa.html

I kode:
`* ^identifier.system = "oid" // Har ikke funnet noe annet enn "oid" under, leter etter offisiell URI, returnerer ERROR i ig-publisher`

Som nevnt har jeg faktisk ikke funnet noe på nettet hva en god system-URI/URL er for OID.

**Comment by rockphotog** [comment]
Lurer på om man bare skal bruke ```
urn:oid:1.2.3.4
``` først som sist og IKKE bruke system.

**Comment by rockphotog** [comment]
[RFC'en](https://www.ietf.org/rfc/rfc3001.txt) sier dog bare URN for OID er "oid", altså, "urn:oid", men eksemplene inkluderer en oid, type "urn:oid:1.2.3.x". 

HL7 skriver:

>As defined by RFC 3986  (with many schemes defined in many RFCs). For OIDs and UUIDs, use the URN form (urn:oid:  (note: lowercase) and urn:uuid: 

[Kilde](https://hl7.org/fhir/2021mar/identifier-registry.html) 

Det som det ikke eksplisitt står er at man da *IKKE* skal benytte *system* sammen med OID, bare *value* som starter med "urn:oid:x.x.x", så er det vel "urn:ietf:rfc:3986" som er riktig for *system*.

**Comment by rockphotog** [comment]
@thomiz Kan du generere doc på nytt for å se om error forsvinner?

**Comment by thomiz** [comment]
Ja det skal være "urn:ietf:rfc:3986"

Det er bare å trykke på knappen :-)

![image](https://user-images.githubusercontent.com/6229665/151576857-be51330b-92cd-45eb-9ac2-069261bb5f02.png)

**Comment by thomiz** [comment]
Hmm. virker fremdeles ikke...
