### ISSUE TITLE
Spørsmål etter QA

### ISSUE THREAD

**Issue by avgehelse** [HL7Norway/kodeverk#19]
Har tatt en kjapp QA, og har et par spm:

Kodeverk 8116: Her er det noe klipp7lim feil, og litt for mange "f"`er i verdiene nedover. Lurer også på hvorfor Svensk og dansk personnummer er kommentert bort, og i tillegg ligger på linja under?

Kodeverk 8264: Trenger vi egentlig å publisere codesystem når kodeverket er utgått?

Kodeverk 8268: Hvorfor er Svensk og dansk personnummer er kommentert bort i linje 28 og 29, og i tillegg ligger på linja under?

**Comment by rockphotog** [comment]
Kodeverk 8116: Skal se på f'ene. De er kommentert bort fordi de har med en ' som kanskje ikke støttes (men de er med uten ' ).

Kodeverk 8264: Nei, er bare med fordi den var på NILAR sin bruttoliste. 

Kodeverk 8268: Samme som for 8116. Jeg skal bare fjerne de kommenterte linjene, og opprette en issue for å finne ut hvordan vi skal representere spesialtegn.
