### ISSUE TITLE
Oppdatere beskrivelser?

### ISSUE THREAD

**Issue by avgehelse** [HL7Norway/kodeverk#20]
Vi har idag hatt en gjennomgang av beskrivelser for noen av kodeverkene. 
Foreslår at disse oppdateres før vi setter codesystems som active. 
Sender egen epost på disse

**Comment by rockphotog** [comment]
## Arbeidsliste per 2022-02-04T14:40

OID |   | Navn på kodeverk/kodetekst | Forslag ny   beskrivelse/forklaring
-- | -- | -- | --
"7305" | 2.16.578.1.12.4.1.1.7305 | Moderator | Tilleggsopplysning   til diagnose.
"8116" | 2.16.578.1.12.4.1.1.8116 | Id-type for personer | Angir type identifikator for   personer.
  | HNR | H-nummer | Virksomhetsinternt hjelpenummer
  | DNR | D-nummer | Nummer som kan   tildeles personer uten norsk fødselsnummer
  | HER | HER-id | Identifikator   som unikt identifiserer en    kommunikasjonspart i Adresseregisteret.
  | DUF | DUF-nummer | Registreringsnummeret  i UDIs datasystem
"8202" | 2.16.578.1.12.4.1.1.8202 | Type laboratoriemelding | Fagområde innen   laboratoriemedisin og bildediagnstikk. Benyttes for å angi type svarrapport
  | CLIN |   | Fjerne   "Tidl. Klinisk kjemi"
"8268" | 2.16.578.1.12.4.1.1.8268", | Type identifikator | Angir type   identifikator for person og virksomhet.
  | HNR |   | Virksomhetsinternt   hjelpenummer
  | HER | HER-id | Identifikator   som unikt identifiserer en    kommunikasjonspart i Adresseregisteret.
  | DUF | DUF-nummer | Registreringsnummeret  i UDIs datasystem
"8327" | :2.16.578.1.12.4.1.1.8327", | Offisiell personidentifikasjon | Angir type   identifikator for person
  | HNR |   | Virksomhetsinternt   hjelpenummer

**Comment by rockphotog** [comment]
Closed by #21
