### ISSUE TITLE
QA NamingSystems

### ISSUE THREAD

**Issue by rockphotog** [HL7Norway/kodeverk#23]
QA og sette *draft* til *active*

https://github.com/HL7Norway/kodeverk/tree/main/input/fsh/namingsystems

**Comment by thomiz** [comment]
De andre no-basis NamingSystem benytter ikke no-basis-xxx formatet men har uri som dette:
http://hl7.no/fhir/NamingSystem/HPR

[HPR](https://simplifier.net/HL7Norwayno-basis/2.16.578.1.12.4.1.4.4/~xml)

Sjekk ut disse DSTU2 profilene da:
[HL7 Norge DSTU2](https://www.hl7.no/fhir/profiles/Labresultat_og_rekvirent/Generated/Chapter.4.Registry/namingsystems.html)

**Comment by thomiz** [comment]
Skal vi legge disse inn i no-basis? @rockphotog

**Comment by thomiz** [comment]
Eller ser det greit ut, men vi må kanskje endre URI'ene

**Comment by rockphotog** [comment]
Jeg har egentlig prøvd å bygge de over samme lest, hvis du f.eks. ser på 
https://github.com/HL7Norway/kodeverk/blob/main/input/fsh/namingsystems/no-basis-apotekenes-konsesjonsnr.fsh 
og HPR som du peker på, men ser at jeg har truffet der og bommet grovt på de to andre. 

De to avvikene: 
`http://hl7.no/fhir/NamingSystem/no-basis-her-id` -> `http://hl7.no/fhir/NamingSystem/HERid` (eller helst "herid", synes mixed capitals er rotete...)
`http://hl7.no/fhir/NamingSystem/no-basis-resh-id` -> `http://hl7.no/fhir/NamingSystem/RESHid`

For org.nr har jeg funnet denne: `http://data.brreg.no/begrep/28155`
Men det er ID'en for *begrepet*, som *kan* være avvikende som konsept-id/namespace -- men jeg tror det vil fungere godt til vårt formål. Vi får ta en telefon, i mellomtiden lager jeg en versjon bygd på data.norge.no. 

Kilde: https://data.norge.no/concepts/f6639f5e-280e-4dbb-991e-3faca3bf622c

**Comment by rockphotog** [comment]
Kladder på orgnr her:
https://github.com/HL7Norway/kodeverk/blob/dev-namespace-orgnr/input/fsh/namingsystems/no-basis-organisasjonsnummer.fsh
