### ISSUE TITLE
Synk av kodeverk opp mot volven.no pr 5. mai 2022

### ISSUE THREAD

**Issue by josteinven** [HL7Norway/kodeverk#33]
@rockphotog @thomiz Har oppdatert noen kodeverk, men er i tvil om vi gjør det riktig. Det ser ut til å bli 1 branch pr kodeverk vi oppdaterer. Er det korrekt?

[2022-05-05-Oppdateringer av kodeverk på volven.docx](https://github.com/HL7Norway/kodeverk/files/8651388/2022-05-05-Oppdateringer.av.kodeverk.pa.volven.docx)

**Comment by rockphotog** [comment]
Man kan gjerne oppdatere flere kodeverk i én branch, alt etter hva som er praktisk og oversiktlig.

**Comment by thomiz** [comment]
@rockphotog @josteinven 

En slik gruppe av oppdatering ville jeg antakelig tatt i en branch. Det eneste som kan være lurt å vurdere er om dere klarer å ferdigstille og teste branchen innen rimelig tid, slik at det kan opprettes en Pull Request. Oppdateringer som løper over mange sprinter er som regel uhensiktsmessig (det blir da stor fare for å treffe endringer andre gjennomfører i kodebasen med tidkrevende fletting av koden som resultat), så hvis disse oppdateringene ikke kan gjennomføres iløpet av 2-3 uker bør det splittes opp i passende bolker etter hva dere faktisk har mulighet for å få gjort i løpet av en sprint.

Det er lurt å dokumentere innholdet i oppdateringen som en tekst når dere oppretter pull-request. Dvs at hele det dokumentet kan være dokumentasjon på denne pull-requesten. Den kan da også benyttes til å dokumentere endringene i den nye versjonen av koden, og da bør versjonsnummeret i [sushi-config.yaml](https://github.com/HL7Norway/kodeverk/blob/main/sushi-config.yaml) oppdateres

**Comment by josteinven** [comment]
Ok, takk @thomiz og @rockphotog ! -- Begge deler kan funke tenker jeg. Jeg trenger en kort beskrivelse av hvordan vi unngår å lage ny branch hver gang vi går inn å redigerer et kodesystem.

**Comment by thomiz** [comment]
Du kan opprette en ny branch med et passende navn ("Volven-5-mai" for eksempel) før du begynner arbeidet. @josteinven 

Deretter velger du den nye branchen fra nedtrekksmenyen over brancher før du redigerer filene. 
![image](https://user-images.githubusercontent.com/6229665/167564900-9387512e-5416-482a-bf05-13a1d08a9a3e.png)

Vær obs på at det kan hende man plutselig er tilbake i "master" hvis man laster inn websiden for Github igjen så pass på å redigere i riktig branch, hver gang du velger å editere en fil (dette er betydelig enklere med GitExt klienten på desktop). Man kan gjøre så mange commits til branchen sin man ønsker før man oppretter pull request (Husk forklarende tekst i "commit message" hver gang du committer).

**Comment by josteinven** [comment]
Ok, da tror jeg at jeg forstår. Det er da en branch som jeg vil "slette" (riktig terminologi?): Hvordan gjør jeg det?
![image](https://user-images.githubusercontent.com/104504315/167587104-302a6fe4-74a3-4066-add2-a9f4ec2d6add.png)

**Comment by rockphotog** [comment]
@thomiz Jostein har forket repoet, derfor "usynlig".

**Comment by rockphotog** [comment]
All good, såvidt jeg husker. Lukker.
