### ISSUE TITLE
Behov for å legge til flere kodeverk i implementasjonsguide

### ISSUE THREAD

**Issue by avgehelse** [HL7Norway/kodeverk#36]
Vi har behov for å legge inn 8340 i tillegg til de andre kodeverkene i IG`en.

**Comment by avgehelse** [comment]
@rockphotog @josteinven

**Comment by rockphotog** [comment]
@avgehelse  Klipp og lim! Her er et par maler:
https://github.com/HL7Norway/kodeverk/tree/main/tools

Ellers, når er i riktig katalog/branch:
- Trykk "Add file -> Create new file
- Skriv in filnavn, f.eks. "no-kodeverk-8340.fsh"
- Lim inn fra kladd/mal

**Comment by avgehelse** [comment]
@rockphotog: Ok, to skritt frem og et tilbake. Jeg har fått laget filen, men ser at den ligger "rett på rot" og ikke under input/codesystems? 
Har også fått en liste til fra NHN over flere kodesystemer som skal legges inn. Jeg kan kanskje gjøre det samtidig som 8340, men må bare vite hvordan jeg korrigerer feilen og evt flytter filen til rett sted før jeg jobber videre.. 

@josteinven - tagger deg så du kan følge med

**Comment by rockphotog** [comment]
Liten bug i IG Publisher akkurat nå, håper det kommer ny versjon "innen kort". 

https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/IG.20is.20based.20on.204.2E01.20but.20getting.20error.20regarding.20version.20R5

Logg fra kjøring: 
https://github.com/HL7Norway/kodeverk/runs/8244037650?check_suite_focus=true

**Comment by josteinven** [comment]
Ferdig, lagt inn nytt kodeverk 8340
