### ISSUE TITLE
Navngivning - ikke bruke ".codesystem" utenom for filnavn?

### ISSUE THREAD

**Issue by rockphotog** [HL7Norway/kodeverk#5]
>Anbefaling diskutert 2022-01-27 (Anette, Jostein, Thomas, Espen):
><pre>no-kodeverk-XXXX(.codesystem)</pre>
>XXXX er de fire siste sifrene i OID, som i eksempel 2.16.578.1.12.4.1.1.**1101**.

HL7 ser ikke ut til å ha filendelsen ".codesystem" som en del av navet sitt, kun som (*trommevirvel*) filnavn. 
Eksempel:

| Defining URL: | http://hl7.org/fhir/ValueSet/codesystem-hierarchy-meaning |
|--|--|
| Version: | 4.0.1 |
| Name: | CodeSystemHierarchyMeaning |
| Title: | CodeSystemHierarchyMeaning |
| Definition: | The meaning of the hierarchy of concepts in a code system. |
| OID: | 2.16.840.1.113883.4.642.3.784 (for OID based terminology systems) |

[Kilde eksempel](https://www.hl7.org/fhir/valueset-codesystem-hierarchy-meaning.html)

**Comment by thomiz** [comment]
Hvis du har et kodeverk og et verdisett som inneholder hele dette kodeverket så får de samme id med en slik mal og det er ikke bra.

Hvis du forsøker å mate dette inn i en FHIR server: 
http://hl7.org/fhir/R4/valueset-codesystem-hierarchy-meaning.json.html
http://hl7.org/fhir/R4/codesystem-codesystem-hierarchy-meaning.json.html

Vil du antakelig få feil siden det er ulovlig å ha to ressurser med samme id på samme server.

Men vanligvis vil jo terminologiserveren ikke ta id'en du gir den for god fisk å sette sin egen, for eksempel en random UUID men jeg mener vi bør klare å sette id'er som ikke er likelydende, og da slipper du ikke unna codesystem/valueset i id-verdiene.

**Comment by rockphotog** [comment]
Da lar vi det stå hvis ingen legger inn protest. Lukker denne etter jeg har justert dokumentasjon.

**Comment by rockphotog** [comment]
Utført.
